pre-release-replacements = [
    { file = "README.md", search = "^paystack-rs = \".*\"$", replace = "{{crate_name}} = \"{{version}}\"" },
    { file = "src/lib.rs", search = "^//!     paystack-rs = \".*\"$", replace = "//!    {{crate_name}} = \"{{version}}\"" },
]
pre-release-hook = [
    "git",
    "cliff",
    "-o",
    "CHANGELOG.md",
    "--tag",
    "{{version}}",
]

sign-commit = false
sign-tag = false
push = true
publish = true
allow-branch = ["main"]
