name: Release

on:
  workflow_run:
    workflows: ["Rust test on PR fork", "Run test on main"]
    branches: ["main"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      level:
        description: "Release level (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Release Crate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for git-cliff

      - name: Install git-cliff
        run: cargo install git-cliff

      - name: Generate changelog
        run: git-cliff -o CHANGELOG.md

      - name: Commit changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for release" || echo "no changes"

      - name: Push changelog
        run: git push origin main || echo "no changes"

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Perform Release
        run: |
          LEVEL="${{ github.event.inputs.level || 'patch' }}"
          cargo release $LEVEL --no-confirm
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN}}
